# Generated by Django 4.2.3 on 2023-07-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Titulo")),
                ("poster", models.URLField(max_length=255, verbose_name="Poster")),
                ("genre", models.CharField(max_length=255, verbose_name="Genero")),
                (
                    "rating",
                    models.CharField(max_length=255, verbose_name="Clasificacion"),
                ),
                (
                    "release",
                    models.CharField(max_length=255, verbose_name="Lanzamiento"),
                ),
                ("director", models.CharField(max_length=255, verbose_name="Director")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualizacion"
                    ),
                ),
            ],
            options={
                "verbose_name": "pelicula",
                "verbose_name_plural": "peliculas",
                "ordering": ("-created",),
            },
        ),
    ]
